### ISSUE TITLE
Can this model apply DAIC-WOZ dataset?

### ISSUE THREAD

**Issue by kassy11** [Jiaxin-Ye/DepMamba#1]
Thank you for publishing interesting project!

I am currently working on depression detection using the [DAIC-WOZ](https://dcapswoz.ict.usc.edu/) dataset.
This model is supposed to be trained on D-vlog and LMVD, but can it also be trained on DAIC-WOZ?
Also, what kind of modifications are required to the script in that case?

I would appreciate your response.

**Comment by Jiaxin-Ye** [comment]
Thank you for your attention! 

This project mainly follows the feature extraction setting of [D-Vlog](https://doi.org/10.1609/aaai.v36i11.21483), and we have not conducted extra experiments on the DAIC-WOZ. If you want to run DepMamba on the DAIC-WOZ dataset, you can first extract audio and visual features following the D-Vlog and then build a data loader for it.
