### ISSUE TITLE
Incompatible function arguments in 'causal_conv1d_fwd()'

### ISSUE THREAD

**Issue by rizentan** [Jiaxin-Ye/DepMamba#3]
I am using dataset `LMVD`, `mamba_ssm` and `causal-conv1d` have been successfully compiled. I have set the path in the project and used `extract_lmvd_npy.py` for feature extraction. But when I executed `main.py`, the following error occurred in `selective_scan_interface.py` line 182: 
`TypeError: causal_conv1d_fwd(): incompatible function arguments. The following argument types are supported: 
(arg0: torch.Tensor, arg1: torch.Tensor, arg2: Optional[torch.Tensor], arg3: Optional[torch.Tensor], arg4: Optional[torch.Tensor], arg5: Optional[torch.Tensor], arg6: bool) -> torch.Tensor`. 
Can you help me analyze the reason? Also, what should I do if I want to train with my own dataset.

**Comment by Jiaxin-Ye** [comment]
The main reason might be version inconsistency. You can find the appropriate .whl file for your version on https://github.com/state-spaces/mamba and install it directly.

**Comment by rizentan** [comment]
Thank you very much for your reply.
